//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalonia.MusicStore.Assets.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avalonia.MusicStore.Assets.Langs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买专辑.
        /// </summary>
        public static string btn_BuyAlbum {
            get {
                return ResourceManager.GetString("btn_BuyAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用JS方法.
        /// </summary>
        public static string btn_CallJSMethod {
            get {
                return ResourceManager.GetString("btn_CallJSMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示Popup.
        /// </summary>
        public static string btn_ShowFlyout {
            get {
                return ResourceManager.GetString("btn_ShowFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示网页.
        /// </summary>
        public static string btn_ShowWeb {
            get {
                return ResourceManager.GetString("btn_ShowWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询专辑.
        /// </summary>
        public static string txt_SearchAlbums {
            get {
                return ResourceManager.GetString("txt_SearchAlbums", resourceCulture);
            }
        }
    }
}
